version: "3.8"

services:
  spree:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgres://spree_user:spree_pass@db/spree_db"
      REDIS_URL: "redis://redis:6379/1"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: spree_user
      POSTGRES_PASSWORD: spree_pass
      POSTGRES_DB: spree_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2

volumes:
  pg_data:

